<?xml version="1.0" encoding="utf-8"?>
<Database Name="SLS_HB" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SLS_JC;Persist Security Info=True;User ID=shove" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SLS_JCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_Model" Member="T_Model">
    <Type Name="T_Model">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PlayTypeID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Descption" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>