<?xml version="1.0" encoding="utf-8"?>
<Database Name="SLS_JC" Class="PassRateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SLS_JC;Persist Security Info=True;User ID=shove" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SLS_JCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_PassRate" Member="T_PassRate">
    <Type Name="T_PassRate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Day" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatchNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Game" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MainTeam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GuestTeam" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatchID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Win" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WinDirection" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Flat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FlatDirection" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Lose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LoseDirection" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S10" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S10Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S20" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S20Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S21" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S21Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S30" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S30Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S31" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S31Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S32" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S32Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S40" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S40Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S41" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S41Direction" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="S42" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S42Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="S50" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S50Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="S51" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S51Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="S52" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="S52Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sother" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SotherDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P00" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P00Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P11" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P11Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P22" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P22Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="P33" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P33Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pother" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PotherDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F01" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F01Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F02" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F02Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F12" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F12Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F03" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F03Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F13" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F13Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F23" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F23Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F04" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F04Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F14" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F14Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F24" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F24Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F05" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F05Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F15" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F15Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F25" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F25Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fother" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FotherDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In0" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In0Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In1Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In2Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In3Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In4Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In5Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In6" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In6Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="In7" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="In7Direction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SSDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SPDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SFDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PSDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PPDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PFDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FSDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FPDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FFDirection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MainLoseball" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StopSellTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EuropeSSP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EuropePSP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EuropeFSP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InforMationID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InforMationMainTeamID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InforMationGuestTeamID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="InforMationMatchTypeID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GameColor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SNumberCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PNumberCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FNumberCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsHhad" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCrs" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsTtg" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsHafu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="State" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>