//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace SLS.SilverLight.FilterShrink.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_PassRate", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class T_PassRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DayField;
        
        private string EuropeFSPField;
        
        private string EuropePSPField;
        
        private string EuropeSSPField;
        
        private System.Nullable<double> F01Field;
        
        private string F01DirectionField;
        
        private System.Nullable<double> F02Field;
        
        private string F02DirectionField;
        
        private System.Nullable<double> F03Field;
        
        private string F03DirectionField;
        
        private System.Nullable<double> F04Field;
        
        private string F04DirectionField;
        
        private System.Nullable<double> F05Field;
        
        private string F05DirectionField;
        
        private System.Nullable<double> F12Field;
        
        private string F12DirectionField;
        
        private System.Nullable<double> F13Field;
        
        private string F13DirectionField;
        
        private System.Nullable<double> F14Field;
        
        private string F14DirectionField;
        
        private System.Nullable<double> F15Field;
        
        private string F15DirectionField;
        
        private System.Nullable<double> F23Field;
        
        private string F23DirectionField;
        
        private System.Nullable<double> F24Field;
        
        private string F24DirectionField;
        
        private System.Nullable<double> F25Field;
        
        private string F25DirectionField;
        
        private System.Nullable<double> FFField;
        
        private string FFDirectionField;
        
        private System.Nullable<int> FNumberCountField;
        
        private System.Nullable<double> FPField;
        
        private string FPDirectionField;
        
        private System.Nullable<double> FSField;
        
        private string FSDirectionField;
        
        private System.Nullable<double> FlatField;
        
        private string FlatDirectionField;
        
        private System.Nullable<double> FotherField;
        
        private string FotherDirectionField;
        
        private string GameField;
        
        private string GameColorField;
        
        private string GuestTeamField;
        
        private int IdField;
        
        private System.Nullable<double> In0Field;
        
        private string In0DirectionField;
        
        private System.Nullable<double> In1Field;
        
        private string In1DirectionField;
        
        private System.Nullable<double> In2Field;
        
        private string In2DirectionField;
        
        private System.Nullable<double> In3Field;
        
        private string In3DirectionField;
        
        private System.Nullable<double> In4Field;
        
        private string In4DirectionField;
        
        private System.Nullable<double> In5Field;
        
        private string In5DirectionField;
        
        private System.Nullable<double> In6Field;
        
        private string In6DirectionField;
        
        private System.Nullable<double> In7Field;
        
        private string In7DirectionField;
        
        private System.Nullable<long> InforMationGuestTeamIDField;
        
        private System.Nullable<long> InforMationIDField;
        
        private System.Nullable<long> InforMationMainTeamIDField;
        
        private System.Nullable<long> InforMationMatchTypeIDField;
        
        private System.Nullable<bool> IsCrsField;
        
        private System.Nullable<bool> IsHafuField;
        
        private System.Nullable<bool> IsHhadField;
        
        private System.Nullable<bool> IsTtgField;
        
        private System.Nullable<double> LoseField;
        
        private string LoseDirectionField;
        
        private System.Nullable<int> MainLoseballField;
        
        private string MainTeamField;
        
        private System.Nullable<long> MatchIDField;
        
        private string MatchNumberField;
        
        private System.Nullable<double> P00Field;
        
        private string P00DirectionField;
        
        private System.Nullable<double> P11Field;
        
        private string P11DirectionField;
        
        private System.Nullable<double> P22Field;
        
        private string P22DirectionField;
        
        private System.Nullable<double> P33Field;
        
        private string P33DirectionField;
        
        private System.Nullable<double> PFField;
        
        private string PFDirectionField;
        
        private System.Nullable<int> PNumberCountField;
        
        private System.Nullable<double> PPField;
        
        private string PPDirectionField;
        
        private System.Nullable<double> PSField;
        
        private string PSDirectionField;
        
        private System.Nullable<double> PotherField;
        
        private string PotherDirectionField;
        
        private System.Nullable<double> S10Field;
        
        private string S10DirectionField;
        
        private System.Nullable<double> S20Field;
        
        private string S20DirectionField;
        
        private System.Nullable<double> S21Field;
        
        private string S21DirectionField;
        
        private System.Nullable<double> S30Field;
        
        private string S30DirectionField;
        
        private System.Nullable<double> S31Field;
        
        private string S31DirectionField;
        
        private System.Nullable<double> S32Field;
        
        private string S32DirectionField;
        
        private System.Nullable<double> S40Field;
        
        private string S40DirectionField;
        
        private System.Nullable<double> S41Field;
        
        private string S41DirectionField;
        
        private System.Nullable<double> S42Field;
        
        private string S42DirectionField;
        
        private System.Nullable<double> S50Field;
        
        private string S50DirectionField;
        
        private System.Nullable<double> S51Field;
        
        private string S51DirectionField;
        
        private System.Nullable<double> S52Field;
        
        private string S52DirectionField;
        
        private System.Nullable<double> SFField;
        
        private string SFDirectionField;
        
        private System.Nullable<int> SNumberCountField;
        
        private System.Nullable<double> SPField;
        
        private string SPDirectionField;
        
        private System.Nullable<double> SSField;
        
        private string SSDirectionField;
        
        private System.Nullable<double> SotherField;
        
        private string SotherDirectionField;
        
        private System.Nullable<bool> StateField;
        
        private System.Nullable<System.DateTime> StopSellTimeField;
        
        private System.Nullable<double> WinField;
        
        private string WinDirectionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day {
            get {
                return this.DayField;
            }
            set {
                if ((object.ReferenceEquals(this.DayField, value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuropeFSP {
            get {
                return this.EuropeFSPField;
            }
            set {
                if ((object.ReferenceEquals(this.EuropeFSPField, value) != true)) {
                    this.EuropeFSPField = value;
                    this.RaisePropertyChanged("EuropeFSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuropePSP {
            get {
                return this.EuropePSPField;
            }
            set {
                if ((object.ReferenceEquals(this.EuropePSPField, value) != true)) {
                    this.EuropePSPField = value;
                    this.RaisePropertyChanged("EuropePSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EuropeSSP {
            get {
                return this.EuropeSSPField;
            }
            set {
                if ((object.ReferenceEquals(this.EuropeSSPField, value) != true)) {
                    this.EuropeSSPField = value;
                    this.RaisePropertyChanged("EuropeSSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F01 {
            get {
                return this.F01Field;
            }
            set {
                if ((this.F01Field.Equals(value) != true)) {
                    this.F01Field = value;
                    this.RaisePropertyChanged("F01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F01Direction {
            get {
                return this.F01DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F01DirectionField, value) != true)) {
                    this.F01DirectionField = value;
                    this.RaisePropertyChanged("F01Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F02 {
            get {
                return this.F02Field;
            }
            set {
                if ((this.F02Field.Equals(value) != true)) {
                    this.F02Field = value;
                    this.RaisePropertyChanged("F02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F02Direction {
            get {
                return this.F02DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F02DirectionField, value) != true)) {
                    this.F02DirectionField = value;
                    this.RaisePropertyChanged("F02Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F03 {
            get {
                return this.F03Field;
            }
            set {
                if ((this.F03Field.Equals(value) != true)) {
                    this.F03Field = value;
                    this.RaisePropertyChanged("F03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F03Direction {
            get {
                return this.F03DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F03DirectionField, value) != true)) {
                    this.F03DirectionField = value;
                    this.RaisePropertyChanged("F03Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F04 {
            get {
                return this.F04Field;
            }
            set {
                if ((this.F04Field.Equals(value) != true)) {
                    this.F04Field = value;
                    this.RaisePropertyChanged("F04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F04Direction {
            get {
                return this.F04DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F04DirectionField, value) != true)) {
                    this.F04DirectionField = value;
                    this.RaisePropertyChanged("F04Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F05 {
            get {
                return this.F05Field;
            }
            set {
                if ((this.F05Field.Equals(value) != true)) {
                    this.F05Field = value;
                    this.RaisePropertyChanged("F05");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F05Direction {
            get {
                return this.F05DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F05DirectionField, value) != true)) {
                    this.F05DirectionField = value;
                    this.RaisePropertyChanged("F05Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F12 {
            get {
                return this.F12Field;
            }
            set {
                if ((this.F12Field.Equals(value) != true)) {
                    this.F12Field = value;
                    this.RaisePropertyChanged("F12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F12Direction {
            get {
                return this.F12DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F12DirectionField, value) != true)) {
                    this.F12DirectionField = value;
                    this.RaisePropertyChanged("F12Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F13 {
            get {
                return this.F13Field;
            }
            set {
                if ((this.F13Field.Equals(value) != true)) {
                    this.F13Field = value;
                    this.RaisePropertyChanged("F13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F13Direction {
            get {
                return this.F13DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F13DirectionField, value) != true)) {
                    this.F13DirectionField = value;
                    this.RaisePropertyChanged("F13Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F14 {
            get {
                return this.F14Field;
            }
            set {
                if ((this.F14Field.Equals(value) != true)) {
                    this.F14Field = value;
                    this.RaisePropertyChanged("F14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F14Direction {
            get {
                return this.F14DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F14DirectionField, value) != true)) {
                    this.F14DirectionField = value;
                    this.RaisePropertyChanged("F14Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F15 {
            get {
                return this.F15Field;
            }
            set {
                if ((this.F15Field.Equals(value) != true)) {
                    this.F15Field = value;
                    this.RaisePropertyChanged("F15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F15Direction {
            get {
                return this.F15DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F15DirectionField, value) != true)) {
                    this.F15DirectionField = value;
                    this.RaisePropertyChanged("F15Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F23 {
            get {
                return this.F23Field;
            }
            set {
                if ((this.F23Field.Equals(value) != true)) {
                    this.F23Field = value;
                    this.RaisePropertyChanged("F23");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F23Direction {
            get {
                return this.F23DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F23DirectionField, value) != true)) {
                    this.F23DirectionField = value;
                    this.RaisePropertyChanged("F23Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F24 {
            get {
                return this.F24Field;
            }
            set {
                if ((this.F24Field.Equals(value) != true)) {
                    this.F24Field = value;
                    this.RaisePropertyChanged("F24");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F24Direction {
            get {
                return this.F24DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F24DirectionField, value) != true)) {
                    this.F24DirectionField = value;
                    this.RaisePropertyChanged("F24Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> F25 {
            get {
                return this.F25Field;
            }
            set {
                if ((this.F25Field.Equals(value) != true)) {
                    this.F25Field = value;
                    this.RaisePropertyChanged("F25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F25Direction {
            get {
                return this.F25DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.F25DirectionField, value) != true)) {
                    this.F25DirectionField = value;
                    this.RaisePropertyChanged("F25Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FF {
            get {
                return this.FFField;
            }
            set {
                if ((this.FFField.Equals(value) != true)) {
                    this.FFField = value;
                    this.RaisePropertyChanged("FF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FFDirection {
            get {
                return this.FFDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FFDirectionField, value) != true)) {
                    this.FFDirectionField = value;
                    this.RaisePropertyChanged("FFDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FNumberCount {
            get {
                return this.FNumberCountField;
            }
            set {
                if ((this.FNumberCountField.Equals(value) != true)) {
                    this.FNumberCountField = value;
                    this.RaisePropertyChanged("FNumberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FP {
            get {
                return this.FPField;
            }
            set {
                if ((this.FPField.Equals(value) != true)) {
                    this.FPField = value;
                    this.RaisePropertyChanged("FP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FPDirection {
            get {
                return this.FPDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FPDirectionField, value) != true)) {
                    this.FPDirectionField = value;
                    this.RaisePropertyChanged("FPDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FS {
            get {
                return this.FSField;
            }
            set {
                if ((this.FSField.Equals(value) != true)) {
                    this.FSField = value;
                    this.RaisePropertyChanged("FS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSDirection {
            get {
                return this.FSDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FSDirectionField, value) != true)) {
                    this.FSDirectionField = value;
                    this.RaisePropertyChanged("FSDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Flat {
            get {
                return this.FlatField;
            }
            set {
                if ((this.FlatField.Equals(value) != true)) {
                    this.FlatField = value;
                    this.RaisePropertyChanged("Flat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlatDirection {
            get {
                return this.FlatDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FlatDirectionField, value) != true)) {
                    this.FlatDirectionField = value;
                    this.RaisePropertyChanged("FlatDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Fother {
            get {
                return this.FotherField;
            }
            set {
                if ((this.FotherField.Equals(value) != true)) {
                    this.FotherField = value;
                    this.RaisePropertyChanged("Fother");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotherDirection {
            get {
                return this.FotherDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.FotherDirectionField, value) != true)) {
                    this.FotherDirectionField = value;
                    this.RaisePropertyChanged("FotherDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Game {
            get {
                return this.GameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameField, value) != true)) {
                    this.GameField = value;
                    this.RaisePropertyChanged("Game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameColor {
            get {
                return this.GameColorField;
            }
            set {
                if ((object.ReferenceEquals(this.GameColorField, value) != true)) {
                    this.GameColorField = value;
                    this.RaisePropertyChanged("GameColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuestTeam {
            get {
                return this.GuestTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestTeamField, value) != true)) {
                    this.GuestTeamField = value;
                    this.RaisePropertyChanged("GuestTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In0 {
            get {
                return this.In0Field;
            }
            set {
                if ((this.In0Field.Equals(value) != true)) {
                    this.In0Field = value;
                    this.RaisePropertyChanged("In0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In0Direction {
            get {
                return this.In0DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In0DirectionField, value) != true)) {
                    this.In0DirectionField = value;
                    this.RaisePropertyChanged("In0Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In1 {
            get {
                return this.In1Field;
            }
            set {
                if ((this.In1Field.Equals(value) != true)) {
                    this.In1Field = value;
                    this.RaisePropertyChanged("In1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In1Direction {
            get {
                return this.In1DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In1DirectionField, value) != true)) {
                    this.In1DirectionField = value;
                    this.RaisePropertyChanged("In1Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In2 {
            get {
                return this.In2Field;
            }
            set {
                if ((this.In2Field.Equals(value) != true)) {
                    this.In2Field = value;
                    this.RaisePropertyChanged("In2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In2Direction {
            get {
                return this.In2DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In2DirectionField, value) != true)) {
                    this.In2DirectionField = value;
                    this.RaisePropertyChanged("In2Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In3 {
            get {
                return this.In3Field;
            }
            set {
                if ((this.In3Field.Equals(value) != true)) {
                    this.In3Field = value;
                    this.RaisePropertyChanged("In3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In3Direction {
            get {
                return this.In3DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In3DirectionField, value) != true)) {
                    this.In3DirectionField = value;
                    this.RaisePropertyChanged("In3Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In4 {
            get {
                return this.In4Field;
            }
            set {
                if ((this.In4Field.Equals(value) != true)) {
                    this.In4Field = value;
                    this.RaisePropertyChanged("In4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In4Direction {
            get {
                return this.In4DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In4DirectionField, value) != true)) {
                    this.In4DirectionField = value;
                    this.RaisePropertyChanged("In4Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In5 {
            get {
                return this.In5Field;
            }
            set {
                if ((this.In5Field.Equals(value) != true)) {
                    this.In5Field = value;
                    this.RaisePropertyChanged("In5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In5Direction {
            get {
                return this.In5DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In5DirectionField, value) != true)) {
                    this.In5DirectionField = value;
                    this.RaisePropertyChanged("In5Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In6 {
            get {
                return this.In6Field;
            }
            set {
                if ((this.In6Field.Equals(value) != true)) {
                    this.In6Field = value;
                    this.RaisePropertyChanged("In6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In6Direction {
            get {
                return this.In6DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In6DirectionField, value) != true)) {
                    this.In6DirectionField = value;
                    this.RaisePropertyChanged("In6Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> In7 {
            get {
                return this.In7Field;
            }
            set {
                if ((this.In7Field.Equals(value) != true)) {
                    this.In7Field = value;
                    this.RaisePropertyChanged("In7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string In7Direction {
            get {
                return this.In7DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.In7DirectionField, value) != true)) {
                    this.In7DirectionField = value;
                    this.RaisePropertyChanged("In7Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InforMationGuestTeamID {
            get {
                return this.InforMationGuestTeamIDField;
            }
            set {
                if ((this.InforMationGuestTeamIDField.Equals(value) != true)) {
                    this.InforMationGuestTeamIDField = value;
                    this.RaisePropertyChanged("InforMationGuestTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InforMationID {
            get {
                return this.InforMationIDField;
            }
            set {
                if ((this.InforMationIDField.Equals(value) != true)) {
                    this.InforMationIDField = value;
                    this.RaisePropertyChanged("InforMationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InforMationMainTeamID {
            get {
                return this.InforMationMainTeamIDField;
            }
            set {
                if ((this.InforMationMainTeamIDField.Equals(value) != true)) {
                    this.InforMationMainTeamIDField = value;
                    this.RaisePropertyChanged("InforMationMainTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InforMationMatchTypeID {
            get {
                return this.InforMationMatchTypeIDField;
            }
            set {
                if ((this.InforMationMatchTypeIDField.Equals(value) != true)) {
                    this.InforMationMatchTypeIDField = value;
                    this.RaisePropertyChanged("InforMationMatchTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsCrs {
            get {
                return this.IsCrsField;
            }
            set {
                if ((this.IsCrsField.Equals(value) != true)) {
                    this.IsCrsField = value;
                    this.RaisePropertyChanged("IsCrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsHafu {
            get {
                return this.IsHafuField;
            }
            set {
                if ((this.IsHafuField.Equals(value) != true)) {
                    this.IsHafuField = value;
                    this.RaisePropertyChanged("IsHafu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsHhad {
            get {
                return this.IsHhadField;
            }
            set {
                if ((this.IsHhadField.Equals(value) != true)) {
                    this.IsHhadField = value;
                    this.RaisePropertyChanged("IsHhad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsTtg {
            get {
                return this.IsTtgField;
            }
            set {
                if ((this.IsTtgField.Equals(value) != true)) {
                    this.IsTtgField = value;
                    this.RaisePropertyChanged("IsTtg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Lose {
            get {
                return this.LoseField;
            }
            set {
                if ((this.LoseField.Equals(value) != true)) {
                    this.LoseField = value;
                    this.RaisePropertyChanged("Lose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoseDirection {
            get {
                return this.LoseDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.LoseDirectionField, value) != true)) {
                    this.LoseDirectionField = value;
                    this.RaisePropertyChanged("LoseDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainLoseball {
            get {
                return this.MainLoseballField;
            }
            set {
                if ((this.MainLoseballField.Equals(value) != true)) {
                    this.MainLoseballField = value;
                    this.RaisePropertyChanged("MainLoseball");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainTeam {
            get {
                return this.MainTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.MainTeamField, value) != true)) {
                    this.MainTeamField = value;
                    this.RaisePropertyChanged("MainTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MatchID {
            get {
                return this.MatchIDField;
            }
            set {
                if ((this.MatchIDField.Equals(value) != true)) {
                    this.MatchIDField = value;
                    this.RaisePropertyChanged("MatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchNumber {
            get {
                return this.MatchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchNumberField, value) != true)) {
                    this.MatchNumberField = value;
                    this.RaisePropertyChanged("MatchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> P00 {
            get {
                return this.P00Field;
            }
            set {
                if ((this.P00Field.Equals(value) != true)) {
                    this.P00Field = value;
                    this.RaisePropertyChanged("P00");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P00Direction {
            get {
                return this.P00DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.P00DirectionField, value) != true)) {
                    this.P00DirectionField = value;
                    this.RaisePropertyChanged("P00Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> P11 {
            get {
                return this.P11Field;
            }
            set {
                if ((this.P11Field.Equals(value) != true)) {
                    this.P11Field = value;
                    this.RaisePropertyChanged("P11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P11Direction {
            get {
                return this.P11DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.P11DirectionField, value) != true)) {
                    this.P11DirectionField = value;
                    this.RaisePropertyChanged("P11Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> P22 {
            get {
                return this.P22Field;
            }
            set {
                if ((this.P22Field.Equals(value) != true)) {
                    this.P22Field = value;
                    this.RaisePropertyChanged("P22");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P22Direction {
            get {
                return this.P22DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.P22DirectionField, value) != true)) {
                    this.P22DirectionField = value;
                    this.RaisePropertyChanged("P22Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> P33 {
            get {
                return this.P33Field;
            }
            set {
                if ((this.P33Field.Equals(value) != true)) {
                    this.P33Field = value;
                    this.RaisePropertyChanged("P33");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P33Direction {
            get {
                return this.P33DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.P33DirectionField, value) != true)) {
                    this.P33DirectionField = value;
                    this.RaisePropertyChanged("P33Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PF {
            get {
                return this.PFField;
            }
            set {
                if ((this.PFField.Equals(value) != true)) {
                    this.PFField = value;
                    this.RaisePropertyChanged("PF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PFDirection {
            get {
                return this.PFDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PFDirectionField, value) != true)) {
                    this.PFDirectionField = value;
                    this.RaisePropertyChanged("PFDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PNumberCount {
            get {
                return this.PNumberCountField;
            }
            set {
                if ((this.PNumberCountField.Equals(value) != true)) {
                    this.PNumberCountField = value;
                    this.RaisePropertyChanged("PNumberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PP {
            get {
                return this.PPField;
            }
            set {
                if ((this.PPField.Equals(value) != true)) {
                    this.PPField = value;
                    this.RaisePropertyChanged("PP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PPDirection {
            get {
                return this.PPDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PPDirectionField, value) != true)) {
                    this.PPDirectionField = value;
                    this.RaisePropertyChanged("PPDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PS {
            get {
                return this.PSField;
            }
            set {
                if ((this.PSField.Equals(value) != true)) {
                    this.PSField = value;
                    this.RaisePropertyChanged("PS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PSDirection {
            get {
                return this.PSDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PSDirectionField, value) != true)) {
                    this.PSDirectionField = value;
                    this.RaisePropertyChanged("PSDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Pother {
            get {
                return this.PotherField;
            }
            set {
                if ((this.PotherField.Equals(value) != true)) {
                    this.PotherField = value;
                    this.RaisePropertyChanged("Pother");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PotherDirection {
            get {
                return this.PotherDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PotherDirectionField, value) != true)) {
                    this.PotherDirectionField = value;
                    this.RaisePropertyChanged("PotherDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S10 {
            get {
                return this.S10Field;
            }
            set {
                if ((this.S10Field.Equals(value) != true)) {
                    this.S10Field = value;
                    this.RaisePropertyChanged("S10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S10Direction {
            get {
                return this.S10DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S10DirectionField, value) != true)) {
                    this.S10DirectionField = value;
                    this.RaisePropertyChanged("S10Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S20 {
            get {
                return this.S20Field;
            }
            set {
                if ((this.S20Field.Equals(value) != true)) {
                    this.S20Field = value;
                    this.RaisePropertyChanged("S20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S20Direction {
            get {
                return this.S20DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S20DirectionField, value) != true)) {
                    this.S20DirectionField = value;
                    this.RaisePropertyChanged("S20Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S21 {
            get {
                return this.S21Field;
            }
            set {
                if ((this.S21Field.Equals(value) != true)) {
                    this.S21Field = value;
                    this.RaisePropertyChanged("S21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S21Direction {
            get {
                return this.S21DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S21DirectionField, value) != true)) {
                    this.S21DirectionField = value;
                    this.RaisePropertyChanged("S21Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S30 {
            get {
                return this.S30Field;
            }
            set {
                if ((this.S30Field.Equals(value) != true)) {
                    this.S30Field = value;
                    this.RaisePropertyChanged("S30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S30Direction {
            get {
                return this.S30DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S30DirectionField, value) != true)) {
                    this.S30DirectionField = value;
                    this.RaisePropertyChanged("S30Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S31 {
            get {
                return this.S31Field;
            }
            set {
                if ((this.S31Field.Equals(value) != true)) {
                    this.S31Field = value;
                    this.RaisePropertyChanged("S31");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S31Direction {
            get {
                return this.S31DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S31DirectionField, value) != true)) {
                    this.S31DirectionField = value;
                    this.RaisePropertyChanged("S31Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S32 {
            get {
                return this.S32Field;
            }
            set {
                if ((this.S32Field.Equals(value) != true)) {
                    this.S32Field = value;
                    this.RaisePropertyChanged("S32");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S32Direction {
            get {
                return this.S32DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S32DirectionField, value) != true)) {
                    this.S32DirectionField = value;
                    this.RaisePropertyChanged("S32Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S40 {
            get {
                return this.S40Field;
            }
            set {
                if ((this.S40Field.Equals(value) != true)) {
                    this.S40Field = value;
                    this.RaisePropertyChanged("S40");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S40Direction {
            get {
                return this.S40DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S40DirectionField, value) != true)) {
                    this.S40DirectionField = value;
                    this.RaisePropertyChanged("S40Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S41 {
            get {
                return this.S41Field;
            }
            set {
                if ((this.S41Field.Equals(value) != true)) {
                    this.S41Field = value;
                    this.RaisePropertyChanged("S41");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S41Direction {
            get {
                return this.S41DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S41DirectionField, value) != true)) {
                    this.S41DirectionField = value;
                    this.RaisePropertyChanged("S41Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S42 {
            get {
                return this.S42Field;
            }
            set {
                if ((this.S42Field.Equals(value) != true)) {
                    this.S42Field = value;
                    this.RaisePropertyChanged("S42");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S42Direction {
            get {
                return this.S42DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S42DirectionField, value) != true)) {
                    this.S42DirectionField = value;
                    this.RaisePropertyChanged("S42Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S50 {
            get {
                return this.S50Field;
            }
            set {
                if ((this.S50Field.Equals(value) != true)) {
                    this.S50Field = value;
                    this.RaisePropertyChanged("S50");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S50Direction {
            get {
                return this.S50DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S50DirectionField, value) != true)) {
                    this.S50DirectionField = value;
                    this.RaisePropertyChanged("S50Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S51 {
            get {
                return this.S51Field;
            }
            set {
                if ((this.S51Field.Equals(value) != true)) {
                    this.S51Field = value;
                    this.RaisePropertyChanged("S51");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S51Direction {
            get {
                return this.S51DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S51DirectionField, value) != true)) {
                    this.S51DirectionField = value;
                    this.RaisePropertyChanged("S51Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> S52 {
            get {
                return this.S52Field;
            }
            set {
                if ((this.S52Field.Equals(value) != true)) {
                    this.S52Field = value;
                    this.RaisePropertyChanged("S52");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S52Direction {
            get {
                return this.S52DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.S52DirectionField, value) != true)) {
                    this.S52DirectionField = value;
                    this.RaisePropertyChanged("S52Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SF {
            get {
                return this.SFField;
            }
            set {
                if ((this.SFField.Equals(value) != true)) {
                    this.SFField = value;
                    this.RaisePropertyChanged("SF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SFDirection {
            get {
                return this.SFDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SFDirectionField, value) != true)) {
                    this.SFDirectionField = value;
                    this.RaisePropertyChanged("SFDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SNumberCount {
            get {
                return this.SNumberCountField;
            }
            set {
                if ((this.SNumberCountField.Equals(value) != true)) {
                    this.SNumberCountField = value;
                    this.RaisePropertyChanged("SNumberCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SP {
            get {
                return this.SPField;
            }
            set {
                if ((this.SPField.Equals(value) != true)) {
                    this.SPField = value;
                    this.RaisePropertyChanged("SP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPDirection {
            get {
                return this.SPDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SPDirectionField, value) != true)) {
                    this.SPDirectionField = value;
                    this.RaisePropertyChanged("SPDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SS {
            get {
                return this.SSField;
            }
            set {
                if ((this.SSField.Equals(value) != true)) {
                    this.SSField = value;
                    this.RaisePropertyChanged("SS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSDirection {
            get {
                return this.SSDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SSDirectionField, value) != true)) {
                    this.SSDirectionField = value;
                    this.RaisePropertyChanged("SSDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Sother {
            get {
                return this.SotherField;
            }
            set {
                if ((this.SotherField.Equals(value) != true)) {
                    this.SotherField = value;
                    this.RaisePropertyChanged("Sother");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SotherDirection {
            get {
                return this.SotherDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SotherDirectionField, value) != true)) {
                    this.SotherDirectionField = value;
                    this.RaisePropertyChanged("SotherDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StopSellTime {
            get {
                return this.StopSellTimeField;
            }
            set {
                if ((this.StopSellTimeField.Equals(value) != true)) {
                    this.StopSellTimeField = value;
                    this.RaisePropertyChanged("StopSellTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Win {
            get {
                return this.WinField;
            }
            set {
                if ((this.WinField.Equals(value) != true)) {
                    this.WinField = value;
                    this.RaisePropertyChanged("Win");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinDirection {
            get {
                return this.WinDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.WinDirectionField, value) != true)) {
                    this.WinDirectionField = value;
                    this.RaisePropertyChanged("WinDirection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/DoWork", ReplyAction="http://tempuri.org/IService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetPassRate", ReplyAction="http://tempuri.org/IService/GetPassRateResponse")]
        System.IAsyncResult BeginGetPassRate(string MatchID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> EndGetPassRate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SLS.SilverLight.FilterShrink.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPassRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPassRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SLS.SilverLight.FilterShrink.ServiceReference1.IService>, SLS.SilverLight.FilterShrink.ServiceReference1.IService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPassRateDelegate;
        
        private EndOperationDelegate onEndGetPassRateDelegate;
        
        private System.Threading.SendOrPostCallback onGetPassRateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<GetPassRateCompletedEventArgs> GetPassRateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLS.SilverLight.FilterShrink.ServiceReference1.IService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SLS.SilverLight.FilterShrink.ServiceReference1.IService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SLS.SilverLight.FilterShrink.ServiceReference1.IService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((SLS.SilverLight.FilterShrink.ServiceReference1.IService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLS.SilverLight.FilterShrink.ServiceReference1.IService.BeginGetPassRate(string MatchID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPassRate(MatchID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> SLS.SilverLight.FilterShrink.ServiceReference1.IService.EndGetPassRate(System.IAsyncResult result) {
            return base.Channel.EndGetPassRate(result);
        }
        
        private System.IAsyncResult OnBeginGetPassRate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MatchID = ((string)(inValues[0]));
            return ((SLS.SilverLight.FilterShrink.ServiceReference1.IService)(this)).BeginGetPassRate(MatchID, callback, asyncState);
        }
        
        private object[] OnEndGetPassRate(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> retVal = ((SLS.SilverLight.FilterShrink.ServiceReference1.IService)(this)).EndGetPassRate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPassRateCompleted(object state) {
            if ((this.GetPassRateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPassRateCompleted(this, new GetPassRateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPassRateAsync(string MatchID) {
            this.GetPassRateAsync(MatchID, null);
        }
        
        public void GetPassRateAsync(string MatchID, object userState) {
            if ((this.onBeginGetPassRateDelegate == null)) {
                this.onBeginGetPassRateDelegate = new BeginOperationDelegate(this.OnBeginGetPassRate);
            }
            if ((this.onEndGetPassRateDelegate == null)) {
                this.onEndGetPassRateDelegate = new EndOperationDelegate(this.OnEndGetPassRate);
            }
            if ((this.onGetPassRateCompletedDelegate == null)) {
                this.onGetPassRateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPassRateCompleted);
            }
            base.InvokeAsync(this.onBeginGetPassRateDelegate, new object[] {
                        MatchID}, this.onEndGetPassRateDelegate, this.onGetPassRateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SLS.SilverLight.FilterShrink.ServiceReference1.IService CreateChannel() {
            return new ServiceClientChannel(this);
        }
        
        private class ServiceClientChannel : ChannelBase<SLS.SilverLight.FilterShrink.ServiceReference1.IService>, SLS.SilverLight.FilterShrink.ServiceReference1.IService {
            
            public ServiceClientChannel(System.ServiceModel.ClientBase<SLS.SilverLight.FilterShrink.ServiceReference1.IService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginGetPassRate(string MatchID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = MatchID;
                System.IAsyncResult _result = base.BeginInvoke("GetPassRate", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> EndGetPassRate(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate> _result = ((System.Collections.ObjectModel.ObservableCollection<SLS.SilverLight.FilterShrink.ServiceReference1.T_PassRate>)(base.EndInvoke("GetPassRate", _args, result)));
                return _result;
            }
        }
    }
}
